### ISSUE TITLE
Black window when opening discord canary

### ISSUE THREAD

**Issue by Morphime** [simoniz0r/Discord-Canary-AppImage#2]
I'm having problem since last Discord Canary update... The window just open up full black every time!
I've ran my update script couple of time in case there was a new update fixing it but nope..

![image](https://user-images.githubusercontent.com/7396125/49588653-4a4ddd80-f935-11e8-879c-6edaf331b8f4.png)

**Comment by simoniz0r** [comment]
I'm not having any issues running the AppImage myself... try running it in a terminal to see if you get any errors?

**Comment by Morphime** [comment]
/usr/local/bin/discord-canary.AppImage
DiscordCanary 0.0.62
Starting updater.
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"

**Comment by Morphime** [comment]
> /usr/local/bin/discord-canary.AppImage
> DiscordCanary 0.0.62
> Starting updater.
> Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"

I just reinstalled Discord and it looks all fixed now
