### ISSUE TITLE
Discord Not opening

### ISSUE THREAD

**Issue by Morphime** [simoniz0r/Discord-Canary-AppImage#3]
Since last version, im unable to open discord at all! 
When i run in console heres the result:

fltk-dialog: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by fltk-dialog)
fltk-dialog: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by fltk-dialog)
fltk-dialog: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fltk-dialog)

I also get the same error when i update Discord with my script

**Comment by simoniz0r** [comment]
What distro are you running?

**Comment by Morphime** [comment]
> What distro are you running?

CentOS Linux release 7.5.1804 (Core)

**Comment by simoniz0r** [comment]
Something must have changed about the way fltk-dialog is built which makes it not work on CentOS 7 anymore.  I submitted an issue there.

You should still be able to use Discord Stable or PTB as those are still using an old version of fltk-dialog.

**Comment by Morphime** [comment]
> Something must have changed about the way fltk-dialog is built which makes it not work on CentOS 7 anymore. I submitted an issue there.
> 
> You should still be able to use Discord Stable or PTB as those are still using an old version of fltk-dialog.

Discord Stable is crashing too.... im gunna try PTB

**Comment by Morphime** [comment]
> Something must have changed about the way fltk-dialog is built which makes it not work on CentOS 7 anymore. I submitted an issue there.
> 
> You should still be able to use Discord Stable or PTB as those are still using an old version of fltk-dialog.

Your Discord Stable appimage is running fine! Ill be using this for now

**Comment by simoniz0r** [comment]
The author of fltk-dialog released a new build which was built from Ubuntu 14.04, so it *should* work for you.  I have updated [v0.0.63](https://github.com/simoniz0r/Discord-Canary-AppImage/releases/download/v0.0.63/discord-canary-0.0.63-x86_64.AppImage) with this build of fltk-dialog if you'd like to try it and see it works for you.

**Comment by Morphime** [comment]
> The author of fltk-dialog released a new build which was built from Ubuntu 14.04, so it _should_ work for you. I have updated [v0.0.63](https://github.com/simoniz0r/Discord-Canary-AppImage/releases/download/v0.0.63/discord-canary-0.0.63-x86_64.AppImage) with this build of fltk-dialog if you'd like to try it and see it works for you.

Works perfectly thanks
